spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: chltjswo789@gmail.com
    password: gwxnqnlwbhezmthg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true